repos:
  -   repo: local
      hooks:
          - id: flake8
            exclude: ^(db/models/__init__.py|app/app\.py|test_app/)
            name: flake8
            entry: python -m flake8
            language: system
            types: [ python ]
          - id: isort
            exclude: ^app/(app\.py|source/views\.py)|^db_creation.py|^test_app/
            name: isort
            entry: python -m isort
            language: system
            types: [ python ]
          - id: black
            name: black
            entry: python -m black
            language: system
            types: [ python ]
          - id: mypy
            exclude: ^app/source/(errors\.py|utilities\.py)|^test_app/
            name: mypy
            entry: mypy
            language: system
            types: [ python ]
            args: ["--ignore-missing-imports", "--scripts-are-modules"]
